# Generated by Django 5.1.4 on 2026-08-02 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('starter_code', models.JSONField()),
                ('visible_tests', models.JSONField()),
                ('hidden_tests', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oa_problems',
            },
        ),
        migrations.CreateModel(
            name='OASubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=32)),
                ('source_code', models.TextField()),
                ('test_results', models.JSONField()),
                ('pass_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('ai_review', models.JSONField(blank=True, null=True)),
                ('final_score', models.IntegerField()),
                ('mode', models.CharField(default='graded', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oa_submissions', to='accounts.guestsession')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='oa.oaproblem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oa_submissions', to='accounts.user')),
            ],
            options={
                'db_table': 'oa_submissions',
            },
        ),
    ]
