# Generated by Django 5.1.4 on 2026-08-02 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.JSONField()),
                ('status', models.CharField(default='active', max_length=16)),
                ('current_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='accounts.guestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'interview_sessions',
            },
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField()),
                ('question_type', models.CharField(max_length=16)),
                ('subject', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('score', models.IntegerField()),
                ('feedback', models.TextField(default='')),
                ('correct_answer', models.TextField(default='')),
                ('answer_idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'interview_results',
                'constraints': [models.UniqueConstraint(fields=('session', 'answer_idempotency_key'), name='uq_result_session_idempotency')],
            },
        ),
    ]
