# Generated by Django 5.1.4 on 2026-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['subject', 'sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='note',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF'), ('slides', 'Slides'), ('doc', 'Document'), ('syllabus', 'Syllabus'), ('image', 'Image'), ('link', 'Link'), ('text', 'Text')], default='link', max_length=16),
        ),
        migrations.AddField(
            model_name='note',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['approved', 'subject', 'sort_order'], name='notes_approve_7f9a45_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('subject', 'unit', 'title'), name='uniq_note_subject_unit_title'),
        ),
    ]
