# Generated by Django 5.1.4 on 2026-08-02 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=128)),
                ('subtopic', models.CharField(default='', max_length=128)),
                ('count', models.IntegerField()),
                ('difficulty', models.CharField(max_length=16)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mcq_sets',
            },
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=8)),
                ('explanation', models.TextField(default='')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq.mcqset')),
            ],
            options={
                'db_table': 'mcq_questions',
            },
        ),
        migrations.CreateModel(
            name='McqAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=128)),
                ('difficulty', models.CharField(default='', max_length=16)),
                ('correct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempts', to='accounts.guestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempts', to='accounts.user')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='mcq.mcqset')),
            ],
            options={
                'db_table': 'mcq_attempts',
            },
        ),
    ]
